### ISSUE TITLE
`styles` objects are a potential pain point

### ISSUE THREAD

**Issue by with-heart** [kempsterrrr/b3nz#39]
One of the primary benefits of libraries like Tailwind/Chakra/etc. is that it's easy to rapidly build out your UI. The major reason for this is that it marries your element structure with your styles _in the same place_.

Using a separate `styles` object to store classnames separates the two, which increases the cognitive overhead required to understand/change the code. That could lead to fatigue/pain down the road.

The reason I think that is because using the `styles` object adds an extra step to some of the most common dev tasks in a React project:

1. Want to know what styles an element in your `jsx` has? Don't look at the element, look at this object instead
2. Want to change the styles of an element in your `jsx`? Don't change the element, change this object instead
3. Want to rearrange the structure of your `jsx` (add new wrapper `div`s, nest new things, etc.)? Change the `jsx` and also change this object

3 is especially brutal imo because that could potentially be a lot of changes across two places in the same file at the same time, depending on what you're doing.

imo if you want to keep things more organized like that, you could gain a similar benefit with less overhead by creating wrapper/container components and inlining the styles in `className` props there.

That would let you keep related styles in the same place but you can view/change/restructure with ease. I view that as one of the primary benefits of libs like 

The funny thing about this issue is that I normally talk shit about long-ass `className` strings, but I'd rather have them inline than elsewhere 😆

**Comment by mbuxmann** [comment]
Hi @with-heart 

Yea I agree with all of your points. 

This was just something I've been recently experimenting with on my projects since I've recently moved from chakra to tailwindcss. 

I've noticed the pain recently a lot with large files, scrolling up and then scrolling down and making changes is just tedious and naming those classes is just as bad. 

I've realized that having the CSS as an object might make it look nice (in my opinion) but it isn't worth the practical cost of development. Especially when things are still being changed on a daily basis. 

I'll be definitely moving those styles inline as I make more changes. 

Love the feedback and thank you very much!

**Comment by with-heart** [comment]
> This was just something I've been recently experimenting with on my projects since I've recently moved from chakra to tailwindcss.

Definitely love that! It's always good to experiment. Can't know if something is better if you don't try ya know?

**Comment by mbuxmann** [comment]
100% Agree with you! :)
